ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'BANNER_CREATE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'BANNER_READ';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'BANNER_UPDATE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'BANNER_DELETE';

CREATE TYPE "BannerType_new" AS ENUM (
  'PROMOTION',
  'OFFER',
  'PRODUCT',
  'CATEGORY',
  'CUSTOM'
);

ALTER TABLE "banners"
  ALTER COLUMN "type" TYPE "BannerType_new"
  USING (
    CASE "type"::TEXT
      WHEN 'HERO' THEN 'PROMOTION'
      ELSE "type"::TEXT
    END
  )::"BannerType_new";

DROP TYPE "BannerType";
ALTER TYPE "BannerType_new" RENAME TO "BannerType";

ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'CATEGORY_TOP';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'CATEGORY_MIDDLE';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'PRODUCT_TOP';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'PRODUCT_MIDDLE';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'SHOP_TOP';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'SHOP_MIDDLE';
ALTER TYPE "BannerPosition" ADD VALUE IF NOT EXISTS 'SIDEBAR';

ALTER TABLE "banners"
  ADD COLUMN "imagePublicId" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "mobileImagePublicId" TEXT,
  ADD COLUMN "openInNewTab" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "createdById" TEXT,
  ADD COLUMN "updatedById" TEXT;

ALTER TABLE "banners" ALTER COLUMN "imagePublicId" DROP DEFAULT;

CREATE INDEX "banners_createdById_idx" ON "banners"("createdById");
CREATE INDEX "banners_updatedById_idx" ON "banners"("updatedById");

ALTER TABLE "banners"
  ADD CONSTRAINT "banners_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "users"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "banners"
  ADD CONSTRAINT "banners_updatedById_fkey"
  FOREIGN KEY ("updatedById") REFERENCES "users"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
