export const PERMISSIONS = {
    // Users
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',

    // Products
    PRODUCT_CREATE: 'PRODUCT_CREATE',
    PRODUCT_READ: 'PRODUCT_READ',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_DELETE: 'PRODUCT_DELETE',

    // Categories
    CATEGORY_CREATE: 'CATEGORY_CREATE',
    CATEGORY_READ: 'CATEGORY_READ',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE',
    CATEGORY_DELETE: 'CATEGORY_DELETE',

    // Customers
    CUSTOMER_CREATE: 'CUSTOMER_CREATE',
    CUSTOMER_READ: 'CUSTOMER_READ',
    CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
    CUSTOMER_DELETE: 'CUSTOMER_DELETE',

    // Orders
    ORDER_CREATE: 'ORDER_CREATE',
    ORDER_READ: 'ORDER_READ',
    ORDER_UPDATE: 'ORDER_UPDATE',
    ORDER_DELETE: 'ORDER_DELETE',

    // Employees
    EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
    EMPLOYEE_READ: 'EMPLOYEE_READ',
    EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',

    // Settings
    SETTINGS_READ: 'SETTINGS_READ',
    SETTINGS_UPDATE: 'SETTINGS_UPDATE',
} as const;